// Saf savaş motoru. Phaser, DOM ve window'a bağımlı olamaz (tests/engine-purity.test.ts denetler).
export { Rng } from './rng';
export { Battle } from './battle';
export type { ActionResult, BattleSetup, CanUse, DebugFlags } from './battle';
export { chooseAction } from './ai';
export type { AiChoice, AiConfig, AiPriority, AiProfile } from './ai';
export { advanceTurn, predictQueue, turnProgress } from './turn-order';
export type { TurnSlot } from './turn-order';
export { damageRange, healRange, rollCrit, rollDamage, rollHeal, rollHit, shieldAmount } from './formulas';
export type { DamageSpec, Range } from './formulas';
export { accuracyOf, armorReduction, attributePower, buildDef, deriveStats, evasionOf, hitChance } from './stats';
export { damageSpecFor } from './spec';
export { betMultipliers, betStake } from './gamble';
export { previewForTargets, previewSkill } from './preview';
export type { TargetPreview } from './preview';
export { ATTRIBUTE_NAME, describePassive, describeSkill, TARGET_TEXT } from './skill-info';
export type { EffectDefs } from './skill-info';
export type { SkillInfo } from './skill-info';
export { describeClass, describeStat, primaryBonusInfo } from './stat-info';
export type { PrimaryBonusInfo, StatInfo, StatKind } from './stat-info';
export * as content from './content';
export type { BattleDef, Teams } from './content';
export type * from './types';
