// Saf savaş motoru. Phaser, DOM ve window'a bağımlı olamaz (tests/engine-purity.test.ts denetler).
export { Rng } from './rng';
export { Battle } from './battle';
export type { ActionResult, BattleObserver, BattleSetup, ObservedAction, CanUse, ChoiceLike, DebugFlags, LastActionKind } from './battle';
export { slotOfTileUid, tileUid } from './battle';
export { chooseAction, explainChoice, unitLabel } from './ai';
export type { AiCandidate, AiChoice, AiConfig, AiDifficulty, AiDifficultyConfig, AiExplanation, AiPriority, AiProfile, AiTrace } from './ai';
export { MatchLog, DEFAULT_MAX_CHARS as MATCH_LOG_MAX_CHARS } from './match-log';
export type { MatchLogMeta, MatchLogOptions, MoveRecord, UnitSnap } from './match-log';
export { advanceTurn, predictQueue, turnProgress } from './turn-order';
export type { TurnSlot } from './turn-order';
export { damageRange, healRange, rollCrit, rollDamage, rollHeal, rollHit, rollHitOutcome, shieldAmount } from './formulas';
export type { DamageSpec, Range } from './formulas';
export { battleSummary } from './battle-summary';
export { accuracyOf, applySummonVariant, applyUnitModifiers, hasUnitModifiers, armorReduction, attributePower, buildDef, deriveStats, evasionOf, hitChance, hitOutcome, variantMult } from './stats';
export type { HitOutcome } from './stats';
export { damageSpecFor } from './spec';
export { betMultipliers, betStake } from './gamble';
export { isRatioCost, skillCostAmount, skillCostLabel } from './cost';
export { burnAmountFor, emptyProcApplies, nominalBurn } from './mana-burn';
export { previewForTargets, previewSkill } from './preview';
export type { DoomPreview, TargetPreview } from './preview';
export { ATTRIBUTE_NAME, describeGlobalSkill, describePassive, describeRage, describeSkill, TARGET_TEXT } from './skill-info';
export type { EffectDefs, GlobalSkillInfo } from './skill-info';
export type { SkillInfo } from './skill-info';
export { describeClass, describeStat, primaryBonusInfo } from './stat-info';
export type { PrimaryBonusInfo, StatInfo, StatKind } from './stat-info';
export * as content from './content';
export type { BattleDef, Teams, TeamUnits } from './content';
export type * from './types';
