// Endless ekranının TÜM oyun içi yazıları (İngilizce) tek yerde: ekran yeniden tasarlanırken (ui-dev) metinler buradan okunur / değiştirilir.
// Sahne (src/game/scenes/EndlessScene.ts) yalnızca bu yazıları ve src/endless/format.ts'deki kart/item yazılarını kullanır.
import { ITEMS } from '../progression/items';
import { ENDLESS } from './data';

const pct = (r: number) => `${Math.round(r * 100)}%`;

export const UI_TEXT = {
  back: '◂  BACK',
  yes: 'Yes',
  no: 'No',
  mainMenu: 'Main Menu',
  newRun: 'New Run',
  startRun: 'Start a Run',

  // Başlık ekranı
  title: 'Endless',
  titleSub: 'Wave after wave. A reward after every victory. How far can your company go?',
  continueRun: (wave: number) => `Continue · Wave ${wave}`,
  rules: `Elite every ${ENDLESS.eliteEvery}th wave · Boss every ${ENDLESS.bossEvery}th · Merchant after every ${ENDLESS.shop.every}th`,
  bestRuns: 'BEST RUNS',
  noRuns: 'No runs yet. How far can your company go?',
  scoreWave: (wave: number) => `WAVE ${wave}`,
  scoreTurns: (turns: number) => `${turns} turns`,
  confirmNewRun: 'Start a new run? Your current run ends and its score is recorded.',
  confirmNewRunSuspended: 'Start a new run? The suspended battle is lost, your current run ends and its score is recorded.',

  // Takım seçimi
  pickTitle: 'Choose Your Company',
  pickSub: (n: number) => `Drag ${n} heroes onto the field. They start at level 1 with no gear, and keep their places all run.`,
  pickHint: 'Drag a hero onto a cell, or tap to add or remove. The front row faces the enemy.',
  pickRoster: 'Heroes',
  pickCompany: (n: number, size: number) => `Your company  ${n} / ${size}`,
  pickFront: 'Front ▸',
  pickBack: 'Back',
  pickRemove: 'Drop here to remove',
  pickFull: (size: number) => `Your company is full (${size}). Drop onto a hero to swap them out.`,
  pickMeleeBack: 'Melee: move to the front row to strike.',
  autoArrange: 'Auto Arrange',
  classInfo: (name: string, primary: string, passive?: string) => `${name} · ${primary.toUpperCase()}${passive ? ` · Passive: ${passive}` : ''}`,
  randomize: 'Randomize',
  startRunButton: 'Start Run',

  // Kamp
  campTitle: (wave: number) => `Wave ${wave}`,
  campFoes: (names: string[]) => `Foes: ${names.join(' · ')}`,
  campSpecial: (boss: boolean, name: string) => `${boss ? 'Boss' : 'Elite'} wave · ${name}`,
  campStats: (gold: number, gs: number, cleared: number) => `Gold ${gold}   ·   Gear Score ${gs}   ·   Waves cleared ${cleared}`,
  campBlessing: (hpMult: number, waves: number) => `Hero's Feast: +${pct(hpMult - 1)} max health for ${waves} more ${waves === 1 ? 'wave' : 'waves'}`,
  heroHealth: (ratio: number) => `${pct(ratio)} health`,
  heroRow: (slot: number) => ['Front row', '2nd row', '3rd row', 'Back row'][Math.floor(slot / 3)] ?? '',
  emptySlot: '—',
  fightWave: (wave: number) => `Fight Wave ${wave}`,
  faceBoss: 'Face the Boss',
  abandonRun: 'Abandon Run',
  confirmAbandon: 'Abandon this run? Your score will be recorded.',

  // Ödül
  rewardTitle: 'Victory',
  rewardSub: (cleared: number, special: 'elite' | 'boss' | null) =>
    `Wave ${cleared} cleared${special === 'boss' ? ': the boss has fallen' : special === 'elite' ? ': the elite has fallen' : ''}. Choose one reward.`,
  take: 'Take',
  cardHint: 'Tap a card to claim it.',
  usableBy: 'USABLE BY',
  anyHero: 'Any hero',
  noOneCanWield: 'No one in your party can wield this',
  sell: (gold: number) => `Sell: ${gold}`,
  kickerItem: (special: 'elite' | 'boss' | null) => (special === 'boss' ? 'Boss spoils' : special === 'elite' ? 'Elite spoils' : 'Spoils'),
  kickerGold: (special: 'elite' | 'boss' | null) => (special === 'boss' ? 'Boss bounty' : special === 'elite' ? 'Elite bounty' : 'Coin'),
  kickerHeal: (special: 'elite' | 'boss' | null) => (special ? 'Field surgeon' : 'Rest'),
  kickerFeast: "Hero's feast",
  relicKicker: 'Relic',
  purse: (from: number, to: number) => `Purse ${from} → ${to}`,
  fullHealth: 'FULL HEALTH',
  kickerRevive: 'Revival',
  revive: (name: string) => `Revive ${name}`,
  fallen: 'Fallen',
  shopBagFull: 'The bag is full. Make room in Gear before buying.',
  youHaveGold: (gold: number) => `You have ${gold} gold.`,
  healPreview: (from: number, to: number) => `${pct(from)} → ${pct(to)}`,
  forHero: (cls: string) => `For the ${cls}`,
  suits: (cls: string) => `Suits the ${cls}`,
  toBag: (n: number, max: number) => `Goes to the bag (${n} / ${max})`,
  bagFullDiscard: 'Bag full: discard an item first',
  rareDrop: (name: string) => `Rare drop: ${name} (in your bag)`,
  rareDropWaiting: (name: string) => `Rare drop: ${name}. Bag full: discard an item to take it, or it is left behind`,
  takeRare: (name: string) => `Take ${name}`,
  openBag: (n: number, max: number) => `Bag · ${n}/${max}`,
  gear: 'Gear',
  gearLocked: 'Finish the suspended battle first',
  campBag: (n: number, max: number) => `Bag ${n} / ${max}`,
  replaces: (name: string) => `Replaces ${name}`,
  fillsEmpty: 'Fills an empty slot',
  primaryWarning: "Warning: turns off this hero's primary bonus",
  primaryWarningShort: 'Turns off the primary bonus',

  // Kalıntı
  relicTitle: 'Choose a Relic',
  relicSub: 'The boss has fallen. A relic stays with your company for the whole run.',
  relicTake: 'Claim',
  relicsOwned: 'RELICS',
  relicEffectLabel: 'Whole run',

  // Tüccar (Ömer 2026-10-09, taslak v1 "Travelling cart")
  shopTitle: 'Merchant',
  merchantName: 'Odo the Peddler',
  previewRun: 'Preview run · not saved, not scored',
  merchantSub: 'Travelling merchant · follows the company',
  merchantLines: {
    idle: 'Steel, leather and a lucky charm or two. Honest prices. Well, honest enough.',
    poor: 'That one is beyond your purse, friend. Come back after the next fight.',
    buy: 'A fine choice. Mind the edge, it bites.',
    sell: `I'll take it off your hands. Half its worth, and not a copper more.`,
    sold: 'Pleasure doing business.',
    buyback: 'Changed your mind? Same price, no questions.',
    reroll: 'Fresh from the bottom of the cart. Have a look.',
    bagFull: 'Your bag is bursting, friend. Sell me something first.',
    empty: 'Nothing left on the stall that suits your company.',
  },
  tabBuy: 'Buy',
  tabSell: 'Sell',
  yourPurse: 'YOUR PURSE',
  bagCount: (n: number, max: number) => `Bag ${n} / ${max}`,
  reroll: (cost: number) => `Reroll wares · ${cost}`,
  sold: 'SOLD',
  buy: (price: number) => `Buy · ${price}`,
  sellFor: (price: number) => `Sell · ${price}`,
  buyBack: (price: number) => `Buy back · ${price}`,
  needMore: (n: number) => `Need ${n} more`,
  bagFullShort: 'Bag full',
  soldOut: 'Sold',
  best: 'BEST',
  comparedWith: (cls: string) => `COMPARED WITH ${cls.toUpperCase()}`,
  nowEquipped: (name: string) => `Now: ${name}`,
  slotEmpty: (slot: string) => `${slot} slot is empty`,
  colNow: 'NOW',
  colNew: 'NEW',
  noChange: 'No change',
  yourBag: 'YOUR BAG',
  bagEmpty: 'Your bag is empty.',
  buybackHeading: 'BUYBACK · THIS VISIT',
  buybackEmpty: 'Sold something by mistake? Buy it back here until you move on.',
  sellHint: `The merchant pays ${Math.round(ITEMS.budget.sellRatio * 100)}% of an item's worth.`,
  page: (a: number, b: number) => `${a} / ${b}`,
  toastBought: (name: string) => `${name} added to your bag`,
  toastSold: (name: string, gold: number) => `Sold ${name} for ${gold} gold`,
  toastBoughtBack: (name: string) => `${name} is back in your bag`,
  moveOn: 'Move On',

  // Koşu sonu
  overTitle: (abandoned: boolean) => (abandoned ? 'Run Abandoned' : 'Run Over'),
  overSub: (abandoned: boolean, wave: number) => `${abandoned ? 'Abandoned' : 'Fallen'} at wave ${wave}.`,
  overStats: (cleared: number, turns: number, kills: number, gs: number) => `Waves cleared ${cleared}   ·   Turns ${turns}   ·   Foes slain ${kills}   ·   Gear Score ${gs}`,
  overRank: (rank: number) => (rank === 0 ? 'A new best run!' : rank > 0 ? `#${rank + 1} on your list of best runs.` : 'Not among your best runs this time.'),
} as const;
